In [1]:
# Step 1: Import pandas

# pandas is used to create and manage data in table format
import pandas as pd

In [2]:
# Step 2: Create the dataset

# This dataset shows:
# user    -> who gave the rating
# product -> which product was rated
# rating  -> how much the user liked the product

data = {
    "user": ["Amit", "Amit", "Riya", "Riya", "Sohan", "Sohan", "Neha", "Neha", "Kiran", "Kiran"],
    "product": ["AI Book", "Python Book", "AI Book", "Marketing Book", "Python Book", "Finance Book", "AI Book", "Finance Book", "Marketing Book", "AI Book"],
    "rating": [5, 4, 4, 5, 5, 3, 4, 4, 5, 5]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)

# Display dataset
df

    user         product  rating
0   Amit         AI Book       5
1   Amit     Python Book       4
2   Riya         AI Book       4
3   Riya  Marketing Book       5
4  Sohan     Python Book       5
5  Sohan    Finance Book       3
6   Neha         AI Book       4
7   Neha    Finance Book       4
8  Kiran  Marketing Book       5
9  Kiran         AI Book       5

In [3]:
# Step 3: Inspect the data

# head() shows the first 5 rows
print("First 5 rows:")
print(df.head())

# shape shows number of rows and columns
print("\nShape of dataset:")
print(df.shape)

# info() shows column names, data types, and non-null values
print("\nDataset information:")
print(df.info())

First 5 rows:
    user         product  rating
0   Amit         AI Book       5
1   Amit     Python Book       4
2   Riya         AI Book       4
3   Riya  Marketing Book       5
4  Sohan     Python Book       5

Shape of dataset:
(10, 3)

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user     10 non-null     object
 1   product  10 non-null     object
 2   rating   10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes
None

In [4]:
# Step 4: Understand user-product interactions

# Each row represents one interaction between a user and a product
# This helps businesses understand what users like and dislike

print("User-Product Rating Data:")
print(df)

User-Product Rating Data:
    user         product  rating
0   Amit         AI Book       5
1   Amit     Python Book       4
2   Riya         AI Book       4
3   Riya  Marketing Book       5
4  Sohan     Python Book       5
5  Sohan    Finance Book       3
6   Neha         AI Book       4
7   Neha    Finance Book       4
8  Kiran  Marketing Book       5
9  Kiran         AI Book       5

In [5]:
# Step 5: Find average rating of each product

# groupby("product") groups all rows product-wise
# ["rating"].mean() calculates average rating for each product
# sort_values(ascending=False) sorts products from highest to lowest rating

product_ratings = df.groupby("product")["rating"].mean().sort_values(ascending=False)

# Display average rating by product
print("Average Rating of Each Product:")
print(product_ratings)

Average Rating of Each Product:
product
Marketing Book    5.0
AI Book           4.5
Python Book       4.5
Finance Book      3.5
Name: rating, dtype: float64

In [6]:
# Step 6: Convert the result into a DataFrame for better display

# reset_index() converts the grouped result into a normal table
recommendations = product_ratings.reset_index()

# Rename column names for better presentation
recommendations.columns = ["Product", "Average Rating"]

# Display recommendation table
recommendations

          Product  Average Rating
0  Marketing Book             5.0
1         AI Book             4.5
2     Python Book             4.5
3    Finance Book             3.5

In [7]:
# Step 7: Show top recommended products

# head(3) gives the top 3 most highly rated products
top_recommendations = recommendations.head(3)

print("Top Recommended Products:")
print(top_recommendations)

Top Recommended Products:
          Product  Average Rating
0  Marketing Book             5.0
1         AI Book             4.5
2     Python Book             4.5

In [8]:
# Step 8: Business interpretation

# These top-rated products can be:
# 1. shown on the homepage
# 2. recommended to new users
# 3. promoted in email campaigns
# 4. used for upselling and cross-selling

print("Business Interpretation:")
print("The products shown above have the highest average ratings.")
print("These can be recommended first to improve customer engagement and sales.")

Business Interpretation:
The products shown above have the highest average ratings.
These can be recommended first to improve customer engagement and sales.

In [9]:
# Step 9: Full recommendation engine result in one view

print("Complete Recommendation Table:")
print(recommendations)

print("\nTop 3 Recommended Products:")
print(top_recommendations)

Complete Recommendation Table:
          Product  Average Rating
0  Marketing Book             5.0
1         AI Book             4.5
2     Python Book             4.5
3    Finance Book             3.5

Top 3 Recommended Products:
          Product  Average Rating
0  Marketing Book             5.0
1         AI Book             4.5
2     Python Book             4.5

“This is a popularity-based recommendation engine. It checks which products received the highest average ratings and recommends those products first. In real companies like Amazon, Netflix, and YouTube, the logic becomes more advanced, but the purpose remains the same: show relevant items to users.”